### ISSUE TITLE
Getting an error on Home Assistant startup - ValueError: entity_category must be a valid EntityCategory instance

### ISSUE THREAD

**Issue by r3dsouza** [CJNE/ha-myenergi#165]
I recently noticed that I get the following error when re starting HA. The integration seems to be working fine. 
Is there a way to get rid of this error??

    2022-06-02 17:18:36 ERROR (MainThread) [homeassistant.components.number] Error adding entities for domain number with platform myenergi
    Traceback (most recent call last):
      File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
        await asyncio.gather(*tasks)
      File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 514, in _async_add_entity
        entry = entity_registry.async_get_or_create(
      File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 383, in async_get_or_create
        raise ValueError("entity_category must be a valid EntityCategory instance")
    ValueError: entity_category must be a valid EntityCategory instance

    2022-06-02 17:18:36 ERROR (MainThread) [homeassistant.components.number] Error while setting up myenergi platform for number
    Traceback (most recent call last):
      File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
        await asyncio.gather(*pending)
      File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
        await asyncio.gather(*tasks)
      File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 514, in _async_add_entity
        entry = entity_registry.async_get_or_create(
      File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 383, in async_get_or_create
        raise ValueError("entity_category must be a valid EntityCategory instance")
    ValueError: entity_category must be a valid EntityCategory instance

**Comment by r3dsouza** [comment]
I took a deeper look into this and realised that this [breaking change](https://github.com/home-assistant/core/pull/69015) is the cause of the error.

Investigating further, the changes required are to the `number.py` source file. It requires the following changes:
- Change the line 
`from homeassistant.const import ENTITY_CATEGORY_CONFIG` to `from homeassistant.helpers.entity import EntityCategory`. 
- Change every reference to `ENTITY_CATEGORY_CONFIG` with `EntityCategory.CONFIG`

Hope this helps.

**Comment by CJNE** [comment]
Thank you, new version is being published :)
