### ISSUE TITLE
HA does not start after update to 0.0.22

### ISSUE THREAD

**Issue by kanzlerac** [CJNE/ha-myenergi#352]
After updating myenergi integration to 0.0.22 on my Home Assistant (docker compose, version 2023.3.1) I get following error: 

2023-04-05 00:20:00.486 ERROR (Recorder) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 330, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 135, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 390, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 600, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 565, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/myenergi/sensor.py", line 536, in state
    value = operator.attrgetter(self.meta["prop_name"])(self.device)
  File "/usr/local/lib/python3.10/site-packages/pymyenergi/zappi.py", line 222, in pwm
    return self._data.get("pwm") / 100
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

**Comment by nl0pvm** [comment]
The error you paste here was introduced with version 0.0.21 and is still there in 0.0.22. I was able to rollback to 0.0.20

**Comment by CJNE** [comment]
Ouch, sorry! Fixing now...
