### ISSUE TITLE
Entities not updating after update.

### ISSUE THREAD

**Issue by MarkLofthouse** [CJNE/ha-myenergi#501]
Updated to the latest version of the integration yesterday, and the update of my entities seem to be intermittent.

The following is appearing regularly in the HA logs.

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 261, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 417, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 183, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 497, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 992, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1113, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1050, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 998, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/myenergi/sensor.py", line 740, in state
    value = operator.attrgetter(self.meta["prop_name"])(self.device)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Eddi' object has no attribute 'num_phases'

**Comment by CJNE** [comment]
Sorry about that, should be fixed in 0.0.27 :)

**Comment by MarkLofthouse** [comment]
Thanks - soon as HA sees the update will check and report back.

**Comment by MarkLofthouse** [comment]
> Thanks - soon as HA sees the update will check and report back. 

Working great! Thanks
