### ISSUE TITLE
setting up fails

### ISSUE THREAD

**Issue by PietPietPietPietPiet** [CJNE/ha-myenergi#601]
## Version of the custom_component

version 0.0.29

## Configuration

```yaml
Add your logs here.
```

## Describe the bug

After adding the integration in HA using HACS and I can succesfully add my hub but I get an error message "no devices or entities" "setup failed" 
It used to work, probably stopped after an update. Tried to remove and re-install several times to no avail.

## Debug log

Logger: homeassistant.config_entries
Bron: config_entries.py:594
Eerst voorgekomen: 20:29:41 (1 gebeurtenissen)
Laatst gelogd: 20:29:41

Error setting up entry Hub_12154946 for myenergi
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myenergi/__init__.py", line 54, in async_setup_entry
    conn = await hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Connection.__init__() takes from 1 to 6 positional arguments but 7 were given

```

**Comment by Ulrar** [comment]
Same here with 0.0.29.

Downgrading back to 0.0.28 works

**Comment by Ulrar** [comment]
The solution here seems to solve it : https://github.com/music-assistant/hass-music-assistant/issues/3152#issuecomment-2470393980

Although I had to delete my /config/deps/asyncio folder a second time after upgrading to 0.0.29 to get HA to start

**Comment by PietPietPietPietPiet** [comment]
Thanks.

Op wo 13 nov 2024, 10:32 p.m. schreef Kevin Lemonnier <
***@***.***>:

**Comment by G6EJD** [comment]
How come no-one else is seeing this apparent conflict, or is this just a lack of knowledge, finger trouble or conflicts with other HA installations? It's not an integration issue and should be closed.

**Comment by Ulrar** [comment]
From other issues, it seems to be an issue with upstream HA's new dependency management through uv installing stuff in the wrong place.
Depending on what you already have and which order things go in some are affected and some not, but yes it's an HA core issue

**Comment by PietPietPietPietPiet** [comment]
I moved to an entire new HA-OS instance on a virtual machine which I intended to do anyhow. This fixed the problem and I was able to use 0.29. When I exported the configuration and imported it on the destination machine (also a KVM VM) version 0.29 gave he same error. Reverting it to 0.28 fixed the problem.

**Comment by PietPietPietPietPiet** [comment]
In ha-os you can install myenrgi from HACS after adding the repository. No need for any manual configuration. I cannot find the /config/deps/asyncio anywhere. Upgrading 0.28 to 0.29 from the ha gui gives the same error again. Reverting to the snapshot I made of the VM before the upgrade fixed it again.

**Comment by Ulrar** [comment]
As far as I know the issue is the same regardless of what you run it on, you need that env var because HA core installs the deps in one place and uses them in a different place.
It'll install, but the integration won't load

Anyway, unrelated to this project, it's a core issue

**Comment by PietPietPietPietPiet** [comment]
Ok, thanks for the clarification.

Op vr 15 nov 2024, 2:35 p.m. schreef Kevin Lemonnier <
***@***.***>:

**Comment by G6EJD** [comment]
Now overtaken by events and updates.
